### ISSUE TITLE
ci6.googleusercontent.com

### ISSUE THREAD

**Issue by bestpika** [Marnix0810/HackeyBlock-Blocking-lists#1]
**Full domain name (do not use wildcards like asterisks, specify the domain like it's listed.):**  ci6.googleusercontent.com

**On which list(s) is this domain listed:**

*(only select those where it needs to be removed from)*

- [x] HackeyBlock (ads)
- [ ] HackeyPrivacy (tracking)
- [ ] HackeyKids (adult content)
- [ ] HackeySafety (malicious sites)

**Why does it need to be removed?**

- [x] Page breaking
- [x] Does not host unwanted content
- [ ] **Others:** please specify

**Any extra information: (not required)**

Breaks Gmail: Gmail can't show some images because of the block of this domain.

**Comment by Marnix0810** [comment]
Ok, I had it listed as a domain hosting ads. Seems like it hosts all types of media used by Google's webpages?

**Comment by Marnix0810** [comment]
The domain name has been removed.

Thank you for your contribution @bestpika!
